name: Validate Codeowners

on:
  pull_request:
    paths:
        - '.github/CODEOWNERS'

jobs:
  validate-codeowners:
    runs-on: self-hosted
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4

      - uses: mszostok/codeowners-validator@v0.7.4
        if: github.event.pull_request.head.repo.full_name == github.repository
        name: "Full check of CODEOWNERS"
        with:
          checks: "duppatterns,owners,syntax"
          experimental_checks: "notowned"
          github_access_token: "${{ secrets.secrets.GITHUB_TOKEN }}"

      - uses: mszostok/codeowners-validator@v0.7.4
        if: github.event.pull_request.head.repo.full_name != github.repository
        name: "Syntax check of CODEOWNERS"
        with:
          checks: "duppatterns,syntax"
